---
 working_dir: '.'
 fname_dataset: 'dataset/em_train.smi'
 fname_fps: 'dataset/em_fps.pkl'
 fname_tokenizer: '.tokenizer.pkl'
 fname_rnn_parameters: 'parameters/rnn.param'
 fname_vae_encoder_parameters: 'parameters/encoder.param'
 fname_vae_decoder_parameters: 'parameters/decoder.param'
 sampled_dir: 'sampled'
 target_sample_dir: 'target_sample'
 maxLength: 128
 batch_size: 512
 num_epoch: 60
 lr: 1.0e-4


 rnn_param:
  embedding_dim: 256
  hidden_dim: 384
  num_hidden: 3

 vae_param:
  fc_dims: [2048, 512, 128]
  latent_dim: 64
  hidden_dim: 384
  num_hidden: 3
